class AddFleshToEatery < ActiveRecord::Migration
  def change
    add_column :eateries, :adult_dinner_menu_url, :string
    add_column :eateries, :wine_list, :string
    add_column :eateries, :dinner_hours, :string
    add_column :eateries, :child_breakfast_menu_url, :string
    add_column :eateries, :breakfast_hours, :string
    add_column :eateries, :adult_breakfast_menu_url, :string
    add_column :eateries, :requires_pre_payment, :string
    add_column :eateries, :dress, :string
    add_column :eateries, :overall_rating, :string
    add_column :eateries, :counter_quality_rating, :string
    add_column :eateries, :awards, :string
    add_column :eateries, :requires_credit_card, :string
    add_column :eateries, :category_code, :string
    add_column :eateries, :phone_number, :string
    add_column :eateries, :parking, :string
    add_column :eateries, :lunch_hours, :string
    add_column :eateries, :counter_value_rating, :string
    add_column :eateries, :child_dinner_menu_url, :string
    add_column :eateries, :cuisine, :string
    add_column :eateries, :bar, :string
    add_column :eateries, :thumbs_up, :string
    add_column :eateries, :table_quality_rating, :string
    add_column :eateries, :service_rating, :string
    add_column :eateries, :extinct_on, :string
    add_column :eateries, :entree_range, :string
    add_column :eateries, :cost_code, :string
    add_column :eateries, :adult_lunch_menu_url, :string
    add_column :eateries, :table_value_rating, :string
    add_column :eateries, :opened_on, :string
    add_column :eateries, :friendliness_rating, :string
    add_column :eateries, :portion_size, :string
    add_column :eateries, :district_id, :integer
    add_column :eateries, :credit, :string
    add_column :eateries, :disney_permalink, :string
    add_column :eateries, :code, :string
    add_column :eateries, :short_name, :string
    add_column :eateries, :dbf_permalink, :string
    add_column :eateries, :service, :string
    add_column :eateries, :type_of_food, :string
    add_column :eateries, :disney_dining_plan, :string
    add_column :eateries, :tables_in_wonderland, :string
    add_column :eateries, :menu, :text
    add_column :eateries, :important_info, :text
    add_column :eateries, :famous_dishes, :text
    add_column :eateries, :you_might_also_like, :text
    add_column :eateries, :dfb_posts, :text
    add_column :eateries, :dfb_permalink, :string
    add_column :eateries, :location, :string
    add_column :eateries, :flickr_search_term, :string
    add_column :eateries, :touring_plans_permalink, :text
    add_column :eateries, :accepts_tiw, :string
    add_column :eateries, :kosher_available, :string
    add_column :eateries, :accepts_reservations, :string
    add_column :eateries, :house_specialties, :text
    add_column :eateries, :location_details, :text
    add_column :eateries, :published_on, :datetime
  end
end
