$(document).ready ->
  L.mapbox.accessToken = 'pk.eyJ1IjoiY2FwdHByb3RvbiIsImEiOiI3cDFLWWRnIn0.guU68dUaxKCX_MPrZHAesQ'
  queryString = window.location.search
  map = L.mapbox.map('map', 'mapbox.streets').setView([
      28.391
      -81.55
      ], 13)
  myLayer = L.mapbox.featureLayer().addTo(map)
  myLayer.on 'layeradd', (e) ->
    marker = undefined
    popupContent = undefined
    properties = undefined
    marker = e.layer
    properties = marker.feature.properties
    popupContent = '<div class="popup"><h3><a href="/explore/' + properties.id + '" data-toggle="modal" data-target = "#tallModal">' + properties.name + '</a></h3><p class="popup-num">Marker No. ' + properties.name + '</p><p>' + properties.name + '</p></div>'
    marker.bindPopup popupContent,
      closeButton: false
      minWidth: 300
  $.ajax
    dataType: 'text'
    url: '/explore.json' + queryString
    success: (data) ->
      geojson = undefined
      geojson = $.parseJSON(data)
      myLayer.setGeoJSON geojson
  return
# ---
# generated by js2coffee 2.1.0

# # Place all the behaviors and hooks related to the matching controller here.
# # All this logic will automatically be available in application.js.
# # You can use CoffeeScript in this file: http://coffeescript.org/
#
#
#
# # get JSON object
# # on success, parse it and
# # hand it over to MapBox for mapping
# $.ajax
#   dataType: 'text'
#   url: '/explore.json'
#   success: (data) ->
#     geojson = $.parseJSON(data)
#     map.featureLayer.setGeoJSON(geojson)
#
#     # add custom popups to each marker
#     map.featureLayer.on 'layeradd', (e) ->
#       marker = e.layer
#       properties = marker.feature.properties
#
#       # create custom popup
#       popupContent =  '<div class="popup">' +
#                         '<h3>' + properties.name + '</h3>' +
#                         '<p>' + properties.address + '</p>' +
#                       '</div>'
#
#       # http://leafletjs.com/reference.html#popup
#       marker.bindPopup popupContent,
#         closeButton: false
#         minWidth: 320
#
#     # handles a sidebar happy hour click
#     $('article li').click (e) ->
#       current = $(this)
#       currentlyClickedName = current.find('h2').text()
#
#       # opens/closes popup for currently clicked happy hour
#       map.featureLayer.eachLayer (marker) ->
#         if marker.feature.properties.name is currentlyClickedName
#           id = layer._leaflet_id
#           map._layers[id].openPopup()