# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

## when .modal-wide opened, set content-body height based on browser height; 200 is appx height of modal padding, modal title and button bar

centerModal = ->
  $(this).css 'display', 'block'
  $dialog = $(this).find('.modal-dialog')
  # offset = ($(window).height() - $dialog.height()) / 16
  # Center modal vertically in window
  $dialog.css 'margin-top' #, offset
  return

$('.modal').on 'show.bs.modal', centerModal
$(window).on 'resize', ->
  $('.modal:visible').each centerModal
  return

# ---
# generated by js2coffee 2.1.0