# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

## when .modal-wide opened, set content-body height based on browser height; 200 is appx height of modal padding, modal title and button bar

###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

$('.modal-wide').on 'show.bs.modal', ->
  height = $(window).height() - 200
  $(this).find('.modal-body').css 'max-height', height
  return

# ---
# generated by js2coffee 2.1.0